# -*- coding: utf-8 -*-
"""NN_Plot_Predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UwMixlt52SsimJmagP6PhFzWexJLh9K5
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor

# Generate Data
x = np.arange(-10,10, .01)
x = x.reshape(-10,10)

y = x**3 + x**2 - x - 1
y = y.reshape(-10,10)

#creating MLP regressor
net = MLPRegressor(hidden_layer_sizes=(100,), activation='logistic')
net.solver = 'lbfgs'
net.max_iter = 10000

#training NN
net.fit(x,y)

#predict network
y_predict = net.predict(x)

#plotting predicted values
plt.plot(x,y_predict)
plt.legend(['Original', ['NN Prediction']])